### ISSUE TITLE
The "let us know" button in the sandbox leads to a dead-end

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/contribution-tool#151] opened 2023-07-25 16:13 UTC
<img width="1459" alt="Screen Shot 2023-07-25 at 17 09 48" src="https://github.com/OpenTermsArchive/contribution-tool/assets/41474439/b01f0eff-9925-46ff-93ad-451820d1ca80">
<img width="1499" alt="Screen Shot 2023-07-25 at 17 09 37" src="https://github.com/OpenTermsArchive/contribution-tool/assets/41474439/740cd9d0-062e-4ef3-aa1e-c15c643036ac">

**Comment by MattiSG** [comment] 2023-07-27 17:31
Thanks @emmanuellar for reporting!
I cannot reproduce this error, as the link does open an email composing window.
This could be because your system has no `mailto` handler set. Can you please try following [these instructions](https://support.google.com/chrome/thread/57026170/how-to-add-gmail-as-default-mailto-handler?hl=en) and trying again? 🙂

**Comment by emmanuellar** [comment] 2023-07-29 22:20
Thank you Matti for pointing me to this instruction. It worked! 💃

**Comment by MattiSG** [comment] 2023-07-31 10:05
Great! 😃 

When your problem is solved, please close the issue you reported, this enables maintaining a clear list of open problems 🙂 

Could you please suggest a pull request to the documentation website to describe this problem and solution? This is how we will solve it for future users as well 🙂

**Closed by MattiSG** 2023-07-31 10:05 UTC

**Comment by emmanuellar** [comment] 2023-07-31 10:31
I don't know how to go about this. Is there a particular section in the docs that I can add to this? Can I create a PR without adding any code?

**Comment by MattiSG** [comment] 2023-07-31 10:40
Start by identifying the page you would like to add the content to by [navigating the documentation](https://docs.opentermsarchive.org). Once you have found the best location, find the [associated source document](https://github.com/OpenTermsArchive/docs/tree/main/content) and edit it. If there is no existing best location, think of the page where you would like to find it and create that page by clicking “Add file” in the [source folder](https://github.com/OpenTermsArchive/docs/tree/main/content). We can also help you if you get stuck creating the file 🙂
